### ISSUE TITLE
Potential

### ISSUE THREAD

**Issue by aerosmaster** [lionpkqq/StS-BlackRuseMod#10]
## Expected Behavior
is supposed to return to hand when discarded

## Actual Behavior
is staying in the discard pile sometimes when used with flowering night

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by lionpkqq** [comment]
Thanks for the feedback! Still, I could not locate the issue. Was it possibly because your hand was full after triggering [Flowering Night]'s drawing effect? If you had 10 cards in your hand, the [Potential] would not be able to return to your hand.

**Comment by aerosmaster** [comment]
No it wasn't that I only had like 10 cards in the deck and i was discarding
2 potentials with housecleaning I am not sure

**Comment by lionpkqq** [comment]
I believe that I have located the issue and it will be fixed with the next update. Thanks for the feedback!
