### ISSUE TITLE
Daze and Reality Marble 

### ISSUE THREAD

**Issue by 5m1l35** [lionpkqq/StS-BlackRuseMod#11]
Reality marble makes every enemy that uses daze a death sentence if you play it. Do not know if this was in some way intended but with the prevalence of daze enemies this does seriously screw with the temporal archetype I think you were trying to make. Possible fix would to give it a secondary effect were status cards are playable?

**Comment by lionpkqq** [comment]
Thanks for the feedback! It is definitely working as intended. As a power card, you always have the option to not use Reality Marble in fights against enemies that will put dazed in your deck. If you have found certain enemies difficult to defeat, you might wanna use other strategies. GLHF!
