### ISSUE TITLE
Mystery Sword triggers on non damaging cards

### ISSUE THREAD

**Issue by Lunaraia** [lionpkqq/StS-BlackRuseMod#12]
Mystery sword triggers on all cards, even those who are skills and deal no damage, which honestly seems more like a bug than anything to me, would suggest that it's changed to first attack, since with it's current iteration it's unlikely to see much use due to the insane restriction of having to play the attack for double damage before any and all buffs to increase the effect and make the resulting backlash worth it.

**Comment by lionpkqq** [comment]
It used to work as you described but I nerfed it because of its interaction with Temporal cards; however, it seemed like I was over-doing it. I think you are right: I should return it to its original state.
