### ISSUE TITLE
Borrowed Time+ power not matching description

### ISSUE THREAD

**Issue by KongMD-Steam** [lionpkqq/StS-BlackRuseMod#13]
## Expected Behavior
Borrowed Time+ adds a Draw Manipulation debuff to the player for -3 cards next turn.

## Actual Behavior
Borrowed Time+ adds a Draw Manipulation debuff to the player for -5 cards next turn, which is the same as the un-upgraded version.

## Steps to Reproduce the Problem

  1. Play Borrowed Time+

## Specifications

  - Version: 0.8.2
  - Platform: Windows 8.1 x64

**Comment by lionpkqq** [comment]
I believe that I have located the issue and it will be fixed with the next update. Thanks for the feedback!
