### ISSUE TITLE
duplication nifinite

### ISSUE THREAD

**Issue by 5m1l35** [lionpkqq/StS-BlackRuseMod#14]
Again not a bug but a balance concern. If you get two duplication and upgrade one of them you get a very easy infinite where you duplicate the upgraded one and can then duplicate infinitely any attack and one turn any fight with the debuff archetype this is particular strong as it is also infinite block. This may not be a problem as they are rare cards but felt I should bring it to your attention. Congrats on making one of the most enjoyable classes in the game.

**Comment by lionpkqq** [comment]
Alright, it has been patched. Now if you use Duplication on another Duplication, you will get a Madness instead of a Duplication.

Shhh, don't tell the others... :P
