### ISSUE TITLE
Initiator card is overpowered

### ISSUE THREAD

**Issue by KongMD-Steam** [lionpkqq/StS-BlackRuseMod#15]
## Expected Behavior
Initiator is a moderately good card that will be picked in some decks.

## Actual Behavior
The card is currently so powerful, it should always be in every deck, because of its damage potential. 

Here's the math:
If you play all 4 cards in the sequence, it's 77 damage for 5 energy. That's **15.4 dmg per energy**, and it only requires a single card draw. The Backlash debuff from the final card just doesn't matter with that amount of damage output. If you only play 3 cards in the sequence, it's still 10.6 dmg per energy with no downside.

## Steps to Reproduce the Problem

Here's a short video showing how powerful this card is:
[https://streamable.com/pal23](https://streamable.com/pal23)

## Suggested change
I love the concept of this card. Having a fourth card with high damage only after playing three other cards is cool. Here are some damage values that would be more in-line with the base game:

Initiator: 5 damage
Follow Up: 8 damage
Follow Up 2: 10 damage
Finishing Touch: 30 damage

After playing four cards: 53 damage for 5 energy, or 10.6 dmg per energy
After playing three cards: 23 damage for 3 energy, or 7.6 dmg per energy

The change I suggest will only make the card significantly good in decks that spend 5 energy on the card, because only playing 3 cards in the sequence will yield mediocre damage output. That will mean that the card is only significantly good in decks that can spend 5 energy to attack.

**Comment by lionpkqq** [comment]
Thanks for the feedback! I think you are absolutely right. Even without playing the fourth card, Initiator may deal 30 damage in 3 hits, which is much better than Ironclad's Bludgeon, which is a Rare card. It will be nerfed with the next update.
