### ISSUE TITLE
Game Crash W/ Fan Of Knives

### ISSUE THREAD

**Issue by killerjwa** [lionpkqq/StS-BlackRuseMod#16]
## Expected Behavior
Game doesn't crash upon use of fan of knives as a killing blow for The Awakened One

## Actual Behavior
Game crashes

## Steps to Reproduce the Problem

  1. Get to the awakened one with fan of knives
  2. Use fan of knives when it would be the killing blow
  3. Game crashes

## Specifications

  - Version:0.8.5
  - Platform: Steam?
  - Subsystem:

**Comment by lionpkqq** [comment]
Thanks for your feedback! The issue has been located and will be fixed with the next update.
