### ISSUE TITLE
1 Satellite can counterattack multiple times against multi-hit attacks

### ISSUE THREAD

**Issue by DracoOmega** [lionpkqq/StS-BlackRuseMod#17]
## Expected Behavior

When attacked by a multi-hit attack while having 1 satellite, you will counterattack 1 time and the satellite will be consumed.

## Actual Behavior

When attacked by a multi-hit attack while having 1 satellite, you will counterattack every single hit of that attack (ie: 6 times or more) and still lose only one satellite.

Since, if you have enough satellites to match every hit of a multi-hit attacks, one will be consumed per hit, I assume that it is _intended_ that each satellite will only trigger a single time?

**Comment by lionpkqq** [comment]
The 0.9.1 update has fixed this issue.
