### ISSUE TITLE
Game crashes when i beat first monster in a map cant acctually play

### ISSUE THREAD

**Issue by DoomsBelle** [lionpkqq/StS-BlackRuseMod#18]
Game crashes after i beat the fist monster on first floor or when transforming a card using whale cant figure out what is going on please help really want to try out this character

**Comment by lionpkqq** [comment]
Please update the ModTheSpire and the Basemod then check if the issue persists.

**Comment by DoomsBelle** [comment]
Yeah I had to update the base of 😂😂🤦🏻‍♂️

**Comment by lionpkqq** [comment]
Glad I could help.
