### ISSUE TITLE
Consider using the temporary HP mechanic from STSLib instead of Protection

### ISSUE THREAD

**Issue by SilentJ28** [lionpkqq/StS-BlackRuseMod#22]
STSLib / Hubris uses a temporary HP mechanic that has the same effect as protection but is much more visible on the life bar

https://github.com/kiooeht/StSLib/releases/tag/v1.0.0
https://github.com/kiooeht/Hubris

Would be cool if Elegance worked with the temporary HP from those cards as well too.

**Comment by lionpkqq** [comment]
That was exactly the problem. Not only that it would require STSLib to run the mod, but Elegance also wouldn't work properly. Thanks for the suggestion though.
