### ISSUE TITLE
Best Practice upgrades worsen Dilation card

### ISSUE THREAD

**Issue by bug-sniper** [lionpkqq/StS-BlackRuseMod#30]
I played Dilation a few times and then Best Practice. I got Dilation again and saw the preview for its upgrade. It would make the card worse. This is inconsistent with how the cards Apotheosis and Claw work in an unmodded game (in which case Apotheosis increases the Claw's damage by 2 instead of resetting it to 5).

Here is a screenshot of what the problem is:
https://snag.gy/RFlemd.jpg

**Comment by lionpkqq** [comment]
This is just a visual bug. The number of times you use the Dilation wasn't counted in the upgrade screen. If you actually upgraded it, it would work as intended.
