### ISSUE TITLE
Card "FastForward" is display in wrong loc

### ISSUE THREAD

**Issue by rainfoxest** [lionpkqq/StS-BlackRuseMod#34]
## Expected Behavior
Display in ZHT, both card's description and keywords popup

## Actual Behavior
Only this card show in English. And the card's description is different from the one in card.json in loc folder.
![20190112132206_1](https://user-images.githubusercontent.com/31983538/51069625-cb536f80-166d-11e9-9f51-01b2970391d1.jpg)

## Steps to Reproduce the Problem

  1.Get the card from a combat reward

## Specifications

  - Version: 0.9.3 maybe? Steam workshop say last update is from 1 月 11 日 下午 1:56
  - Platform: Steam workshop
  - Subsystem:

**Comment by lionpkqq** [comment]
![image](https://user-images.githubusercontent.com/33392240/51069652-525e0480-15e8-11e9-980d-13694f52f493.png)

I am pretty sure that it happened because you are running multiple mods at the same time and one of the other mods had a card called "Fast Forward" so it created a conflict.

**Comment by rainfoxest** [comment]
Oh you're right, Is the [The Disciple](https://github.com/Tempus/The-Disciple) mod.
Well, that sucks. :(
